### ISSUE TITLE
Proposal: "Advanced features/options" Controls & UI Change

### ISSUE THREAD

**Issue by VarunNSrivastava** [do-me/SemanticFinder#10]
As mentioned in [this comment](https://github.com/do-me/SemanticFinder/pull/4#issuecomment-1602086861), we can probably add a menu for "advanced features". One of these controls should be how we split:

- split by # tokens/chars
- split by sentence 
- split by clause 

We should be able to hide these controls as well as the "# chars" and "threshold" parameter in the advanced features menu.

Additionally, I think it would be best to move the submit button to be at the same line as "query":

<img width="1072" alt="Screen Shot 2023-07-06 at 5 44 37 PM" src="https://github.com/do-me/SemanticFinder/assets/32204417/242ee1e2-e067-44cf-a9e8-906a4fa6c970">

 If this proposal seems like a good idea I'll make the relevant PR.

**Comment by do-me** [comment]
This sounds great! Having the Submit button next to the input seems much more natural indeed. 

I support your proposal about splitting options - did you already find a convenient solution code-wise?
I'd even add a "split by word" option.

Looking forward to your PR!
