### ISSUE TITLE
Use TypeScript 

### ISSUE THREAD

**Issue by lizozom** [do-me/SemanticFinder#16]
As part of my own work with this project, I converted the semantic search part of the project to TypeScript.
Is this something you would be interested in merging?
If so, I could make another PR :-)

**Comment by do-me** [comment]
Thanks for your efforts! So which files did you convert to TS - just `semantic.js` or also `index.js`? 
If it's just `semantic.js` with only 61 lines, maybe adding TS would be overkill? 

I am not an expert on TS but if it helps our contributors we could just as well go for it. We're only 3 people atm so I guess I'll just ping @VarunNSrivastava and ask for your opinion on this.

**Comment by kungfooman** [comment]
> I am not an expert on TS but if it helps our contributors we could just as well go for it.

Every TypeScript dev has to know JavaScript anyway, but not every JavaScript dev requires to know TypeScript, so you pretty much shrink your potential contributer base to a subset.

I liked your initial vision of being "as simple as it gets" and now you are nearly sold by TypeScript... open your eyes, please.
