### ISSUE TITLE
Design logo/icon

### ISSUE THREAD

**Issue by do-me** [do-me/SemanticFinder#20]
If anyone feels creative, it would be nice to have some kind of logo/icon for the project! 
The original version is a little - let's say - rudimentary ;) 

![image](https://github.com/do-me/SemanticFinder/assets/47481567/666dc184-6208-44fb-8667-0152b0355a80)

**Comment by VarunNSrivastava** [comment]
Along these lines, we can also replace the gif in the readme!

**Comment by do-me** [comment]
Just updated the gif ✅

**Comment by do-me** [comment]
I was playing around with SDXL with "magnifying glasses" prompts and found some drafts to be quite interesting: 
![image](https://github.com/do-me/SemanticFinder/assets/47481567/5913a10f-77cb-4b30-88cc-a24b7aef57d3)
![image](https://github.com/do-me/SemanticFinder/assets/47481567/32b482e5-622b-44f7-a3d6-431ec52043f8)
![image](https://github.com/do-me/SemanticFinder/assets/47481567/fece5e24-6ea1-4155-b14b-ccbed3cf5384)

I really liked the last one. 

![image](https://github.com/do-me/SemanticFinder/assets/47481567/541fd9aa-31b8-44c8-ac52-5e35ce47a199)

Apparently SDXL really likes the circle, found it funny that it tried to melt a face, glasses and the magnifying glass with a baseball bat nose :D 

Anyway, came up with a hand-drawn version in excalidraw. If anyone feels creative, feel free to iterate on this one or propose another one! 

![image](https://github.com/do-me/SemanticFinder/assets/47481567/70e857fc-de94-4b49-889c-2a7a8346f7ff)

Excalidraw file here: 

[SemanticFinder.zip](https://github.com/do-me/SemanticFinder/files/12445599/SemanticFinder.zip)

**Comment by VarunNSrivastava** [comment]
I like the hand drawn one! Feel free to put it wherever you like for now and I might try to iterate on it

**Comment by VarunNSrivastava** [comment]
I like the new logo but it is hard to see on the pinned extension. It could use a light background (instead of a transparent one) or some other way of popping out.

**Comment by do-me** [comment]
![image](https://github.com/do-me/SemanticFinder/assets/47481567/4acd5ba4-106d-4c4d-bb3d-700216e359cd)

Agree, will come up with something poppier tonight.

**Comment by do-me** [comment]
![image](https://github.com/do-me/SemanticFinder/assets/47481567/3353ca05-38f8-4844-a112-eacbc311b357)
I've tried a few options. Maybe the middle one is best? 
![image](https://github.com/do-me/SemanticFinder/assets/47481567/baf63878-2ef6-4f29-907e-d768b983030b)

Not really sure, but seems to be more recognizable than before.

**Comment by do-me** [comment]
For now resolved - if anyone has further ideas, I'll reopen.
